version: '3.8'

services:

  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami
    networks:
      - user_network

  kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:19091
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:19091
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka_data:/bitnami
    networks:
      - user_network

  postgres:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: petmatch
      POSTGRES_USER: petmatch
      POSTGRES_PASSWORD: petmatch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user_network

  # === Camunda 8.7 Services ===

  zeebe:
    image: camunda/zeebe:8.7.8
    container_name: zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
    environment:
      - ZEEBE_LOG_LEVEL=debug
    volumes:
      - zeebe_data:/usr/local/zeebe/data
    networks:
      - user_network

  # Используем Bitnami Elasticsearch
  elasticsearch:
    image: bitnami/elasticsearch:8.11.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_ENABLE_SECURITY=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - elastic_data:/bitnami/elasticsearch/data
    networks:
      - user_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  operate:
    image: camunda/operate:8.7.8
    container_name: operate
    ports:
      - "8091:8080"
    environment:
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - LOGGING_LEVEL_ROOT=info
    depends_on:
      elasticsearch:
        condition: service_healthy
      zeebe:
        condition: service_started
    networks:
      - user_network

  tasklist:
    image: camunda/tasklist:8.7.8
    container_name: tasklist
    ports:
      - "8092:8080"
    environment:
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
    depends_on:
      elasticsearch:
        condition: service_healthy
      zeebe:
        condition: service_started
    networks:
      - user_network

volumes:
  kafka_data:
  postgres_data:
  zookeeper_data:
  zeebe_data:
  elastic_data:

networks:
  user_network:
    driver: bridge