bot:
  username: "Meow_sofi_dev_stand_bot"
  TG_TOKEN: "${TG_TOKEN}"
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "message_bot_group"
      auto-offset-reset: earliest
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/common-postgres-db
    username: common-postgres-db-user
    password: common-postgres-db-password
  jpa:
    generate-ddl: true
    show-sql: true